# Generated by Django 5.1.2 on 2024-11-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate_image', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
